/*
 * This source file was generated by the Gradle 'init' task
 */
package com.cst8288.f2024.factoryexample;

/*
TODOS:
    Task 1 : complete open() in JSONFile
    Task 2 : complete open() in PDFFile
    Task 3 : complete createFile in PDFFileCreator
    Task 4 : complete createFile in JSONFileCreator

    Each team member must pick up 1 task, complete it, 
    then create a Pull Request to merge.

*/

public class Client {
   
    public static void main(String[] args) {
        
        FileCreator jsonFileCreator = new JSONFileCreator();
        FileCreator pdfFileCreator = new PDFFileCreator();
      
        Document jsonFile = jsonFileCreator.createFile();
        Document pdfFile = pdfFileCreator.createFile();
        
        System.out.println(jsonFile.open() ); //Outputs: Opening JSON Document
        System.out.println(pdfFile.open() );  //Outputs: Opening PDF Document     
    }
}
