/*
 * This source file was generated by the Gradle 'init' task
 */
package com.cst8288.f2024.factoryexample;

public class Client {
   
    public static void main(String[] args) {
        
        FileCreator jsonFileCreator = new JSONFileCreator();
        FileCreator pdfFileCreator = new PDFFileCreator();
      
        Document jsonFile = jsonFileCreator.createFile();
        Document pdfFile = pdfFileCreator.createFile();
        
        System.out.println(jsonFile.open() ); //Outputs: Opening JSON Document
        System.out.println(pdfFile.open() );  //Outputs: Opening PDF Document     
    }
}
